<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251106105144 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE CRENEAU (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_evenement INTEGER NOT NULL, titre VARCHAR(255) NOT NULL, poste_requis VARCHAR(255) DEFAULT NULL, debut DATETIME NOT NULL, fin DATETIME NOT NULL, max_personnes INTEGER NOT NULL, remarque CLOB DEFAULT NULL, date_creation DATETIME DEFAULT NULL, CONSTRAINT FK_C62375458B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_C62375458B13D439 ON CRENEAU (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__AFFECTATION_TACHE AS SELECT id, id_tache, id_benevole, id_utilisateur, date_affectation, statut, remarque FROM AFFECTATION_TACHE');
        $this->addSql('DROP TABLE AFFECTATION_TACHE');
        $this->addSql('CREATE TABLE AFFECTATION_TACHE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_tache INTEGER NOT NULL, id_benevole INTEGER NOT NULL, id_utilisateur INTEGER DEFAULT NULL, date_affectation DATETIME NOT NULL, statut VARCHAR(20) NOT NULL, remarque CLOB DEFAULT NULL, FOREIGN KEY (id_tache) REFERENCES TACHE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO AFFECTATION_TACHE (id, id_tache, id_benevole, id_utilisateur, date_affectation, statut, remarque) SELECT id, id_tache, id_benevole, id_utilisateur, date_affectation, statut, remarque FROM __temp__AFFECTATION_TACHE');
        $this->addSql('DROP TABLE __temp__AFFECTATION_TACHE');
        $this->addSql('CREATE INDEX IDX_12694ECF7D026145 ON AFFECTATION_TACHE (id_tache)');
        $this->addSql('CREATE INDEX IDX_12694ECFE4DAA34E ON AFFECTATION_TACHE (id_benevole)');
        $this->addSql('CREATE INDEX IDX_12694ECF50EAE44 ON AFFECTATION_TACHE (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__BENEVOLE AS SELECT id, id_utilisateur, remarque, actif FROM BENEVOLE');
        $this->addSql('DROP TABLE BENEVOLE');
        $this->addSql('CREATE TABLE BENEVOLE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_utilisateur INTEGER DEFAULT NULL, remarque CLOB DEFAULT NULL, actif BOOLEAN DEFAULT 1 NOT NULL, FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO BENEVOLE (id, id_utilisateur, remarque, actif) SELECT id, id_utilisateur, remarque, actif FROM __temp__BENEVOLE');
        $this->addSql('DROP TABLE __temp__BENEVOLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7232D39750EAE44 ON BENEVOLE (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__COMMUNICATION AS SELECT id, id_evenement, titre, type, date_prevue, statut, budget, remarque, date_creation FROM COMMUNICATION');
        $this->addSql('DROP TABLE COMMUNICATION');
        $this->addSql('CREATE TABLE COMMUNICATION (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_evenement INTEGER DEFAULT NULL, titre VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT \'post\', date_prevue DATETIME DEFAULT NULL, statut VARCHAR(255) DEFAULT \'brouillon\', budget DOUBLE PRECISION DEFAULT \'0\', notes CLOB DEFAULT NULL, date_creation DATETIME DEFAULT NULL, FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO COMMUNICATION (id, id_evenement, titre, type, date_prevue, statut, budget, notes, date_creation) SELECT id, id_evenement, titre, type, date_prevue, statut, budget, remarque, date_creation FROM __temp__COMMUNICATION');
        $this->addSql('DROP TABLE __temp__COMMUNICATION');
        $this->addSql('CREATE INDEX IDX_DFE3B70E8B13D439 ON COMMUNICATION (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__CONTACT_MESSAGE AS SELECT id, repondu_par_id, nom, email, message, created_at, lu, reponse, repondu_le FROM CONTACT_MESSAGE');
        $this->addSql('DROP TABLE CONTACT_MESSAGE');
        $this->addSql('CREATE TABLE CONTACT_MESSAGE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, repondu_par_id INTEGER DEFAULT NULL, nom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, message CLOB NOT NULL, created_at DATETIME NOT NULL, lu BOOLEAN NOT NULL, reponse CLOB DEFAULT NULL, repondu_le DATETIME DEFAULT NULL, FOREIGN KEY (repondu_par_id) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO CONTACT_MESSAGE (id, repondu_par_id, nom, email, message, created_at, lu, reponse, repondu_le) SELECT id, repondu_par_id, nom, email, message, created_at, lu, reponse, repondu_le FROM __temp__CONTACT_MESSAGE');
        $this->addSql('DROP TABLE __temp__CONTACT_MESSAGE');
        $this->addSql('CREATE INDEX IDX_B609370B26CA41A0 ON CONTACT_MESSAGE (repondu_par_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__CONVENTION AS SELECT id, id_mecene, nom_modele, url_pdf, date_signature, methode_signature, date_creation FROM CONVENTION');
        $this->addSql('DROP TABLE CONVENTION');
        $this->addSql('CREATE TABLE CONVENTION (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_mecene INTEGER NOT NULL, nom_modele VARCHAR(255) DEFAULT NULL, url_pdf VARCHAR(255) DEFAULT NULL, date_signature DATETIME DEFAULT NULL, methode_signature VARCHAR(255) DEFAULT \'aucune\' NOT NULL, date_creation DATETIME DEFAULT NULL, FOREIGN KEY (id_mecene) REFERENCES MECENE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO CONVENTION (id, id_mecene, nom_modele, url_pdf, date_signature, methode_signature, date_creation) SELECT id, id_mecene, nom_modele, url_pdf, date_signature, methode_signature, date_creation FROM __temp__CONVENTION');
        $this->addSql('DROP TABLE __temp__CONVENTION');
        $this->addSql('CREATE INDEX IDX_8EC97841D364722F ON CONVENTION (id_mecene)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__DEMANDE_ANNULATION AS SELECT id, id_affectation, id_benevole, id_admin_reponse, date_demande, statut, motif_benevole, message_admin, date_reponse FROM DEMANDE_ANNULATION');
        $this->addSql('DROP TABLE DEMANDE_ANNULATION');
        $this->addSql('CREATE TABLE DEMANDE_ANNULATION (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_affectation INTEGER NOT NULL, id_benevole INTEGER NOT NULL, id_admin_reponse INTEGER DEFAULT NULL, date_demande DATETIME NOT NULL, statut VARCHAR(20) NOT NULL, motif_benevole CLOB DEFAULT NULL, message_admin CLOB DEFAULT NULL, date_reponse DATETIME DEFAULT NULL, FOREIGN KEY (id_affectation) REFERENCES AFFECTATION_TACHE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_admin_reponse) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO DEMANDE_ANNULATION (id, id_affectation, id_benevole, id_admin_reponse, date_demande, statut, motif_benevole, message_admin, date_reponse) SELECT id, id_affectation, id_benevole, id_admin_reponse, date_demande, statut, motif_benevole, message_admin, date_reponse FROM __temp__DEMANDE_ANNULATION');
        $this->addSql('DROP TABLE __temp__DEMANDE_ANNULATION');
        $this->addSql('CREATE INDEX IDX_75084DE6ECCFAC24 ON DEMANDE_ANNULATION (id_affectation)');
        $this->addSql('CREATE INDEX IDX_75084DE6E4DAA34E ON DEMANDE_ANNULATION (id_benevole)');
        $this->addSql('CREATE INDEX IDX_75084DE625A28D2B ON DEMANDE_ANNULATION (id_admin_reponse)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__DEMANDE_TACHE AS SELECT id, id_tache, id_benevole, id_admin_reponse, date_demande, statut, message_benevole, message_admin, date_reponse FROM DEMANDE_TACHE');
        $this->addSql('DROP TABLE DEMANDE_TACHE');
        $this->addSql('CREATE TABLE DEMANDE_TACHE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_tache INTEGER NOT NULL, id_benevole INTEGER NOT NULL, id_admin_reponse INTEGER DEFAULT NULL, date_demande DATETIME NOT NULL, statut VARCHAR(20) NOT NULL, message_benevole CLOB DEFAULT NULL, message_admin CLOB DEFAULT NULL, date_reponse DATETIME DEFAULT NULL, FOREIGN KEY (id_tache) REFERENCES TACHE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_admin_reponse) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO DEMANDE_TACHE (id, id_tache, id_benevole, id_admin_reponse, date_demande, statut, message_benevole, message_admin, date_reponse) SELECT id, id_tache, id_benevole, id_admin_reponse, date_demande, statut, message_benevole, message_admin, date_reponse FROM __temp__DEMANDE_TACHE');
        $this->addSql('DROP TABLE __temp__DEMANDE_TACHE');
        $this->addSql('CREATE INDEX IDX_44B9A48F7D026145 ON DEMANDE_TACHE (id_tache)');
        $this->addSql('CREATE INDEX IDX_44B9A48FE4DAA34E ON DEMANDE_TACHE (id_benevole)');
        $this->addSql('CREATE INDEX IDX_44B9A48F25A28D2B ON DEMANDE_TACHE (id_admin_reponse)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__DISPONIBILITE_BENEVOLE AS SELECT id, id_benevole, id_evenement, debut, fin, remarque, date_creation FROM DISPONIBILITE_BENEVOLE');
        $this->addSql('DROP TABLE DISPONIBILITE_BENEVOLE');
        $this->addSql('CREATE TABLE DISPONIBILITE_BENEVOLE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_benevole INTEGER NOT NULL, id_evenement INTEGER NOT NULL, debut DATETIME DEFAULT NULL, fin DATETIME DEFAULT NULL, notes CLOB DEFAULT NULL, date_creation DATETIME DEFAULT NULL, FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO DISPONIBILITE_BENEVOLE (id, id_benevole, id_evenement, debut, fin, notes, date_creation) SELECT id, id_benevole, id_evenement, debut, fin, remarque, date_creation FROM __temp__DISPONIBILITE_BENEVOLE');
        $this->addSql('DROP TABLE __temp__DISPONIBILITE_BENEVOLE');
        $this->addSql('CREATE INDEX IDX_FA2761DCE4DAA34E ON DISPONIBILITE_BENEVOLE (id_benevole)');
        $this->addSql('CREATE INDEX IDX_FA2761DC8B13D439 ON DISPONIBILITE_BENEVOLE (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__EVENEMENT AS SELECT id, id_weekend, nom, description, date_debut, date_fin, lieu, heure_debut, duree_minutes, image, date_creation FROM EVENEMENT');
        $this->addSql('DROP TABLE EVENEMENT');
        $this->addSql('CREATE TABLE EVENEMENT (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_weekend INTEGER DEFAULT NULL, nom VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, lieu VARCHAR(255) DEFAULT NULL, heure_debut TIME DEFAULT NULL, duree_minutes INTEGER DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, date_creation DATETIME NOT NULL, FOREIGN KEY (id_weekend) REFERENCES WEEKEND (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO EVENEMENT (id, id_weekend, nom, description, date_debut, date_fin, lieu, heure_debut, duree_minutes, image, date_creation) SELECT id, id_weekend, nom, description, date_debut, date_fin, lieu, heure_debut, duree_minutes, image, date_creation FROM __temp__EVENEMENT');
        $this->addSql('DROP TABLE __temp__EVENEMENT');
        $this->addSql('CREATE INDEX IDX_4FE476F1704F64DE ON EVENEMENT (id_weekend)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__HELLOASSO AS SELECT id, id_evenement, id_externe, prenom, nom, email, telephone, type_ticket, date_achat, date_import FROM HELLOASSO');
        $this->addSql('DROP TABLE HELLOASSO');
        $this->addSql('CREATE TABLE HELLOASSO (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_evenement INTEGER DEFAULT NULL, id_externe VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, type_ticket VARCHAR(255) DEFAULT NULL, date_achat DATETIME DEFAULT NULL, date_import DATETIME DEFAULT NULL, FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO HELLOASSO (id, id_evenement, id_externe, prenom, nom, email, telephone, type_ticket, date_achat, date_import) SELECT id, id_evenement, id_externe, prenom, nom, email, telephone, type_ticket, date_achat, date_import FROM __temp__HELLOASSO');
        $this->addSql('DROP TABLE __temp__HELLOASSO');
        $this->addSql('CREATE INDEX IDX_F90B9E9D8B13D439 ON HELLOASSO (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__HISTORIQUE_EVENEMENT AS SELECT id, id_evenement, id_utilisateur, "action", description, date_action FROM HISTORIQUE_EVENEMENT');
        $this->addSql('DROP TABLE HISTORIQUE_EVENEMENT');
        $this->addSql('CREATE TABLE HISTORIQUE_EVENEMENT (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_evenement INTEGER NOT NULL, id_utilisateur INTEGER DEFAULT NULL, "action" VARCHAR(50) NOT NULL, description CLOB DEFAULT NULL, date_action DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO HISTORIQUE_EVENEMENT (id, id_evenement, id_utilisateur, "action", description, date_action) SELECT id, id_evenement, id_utilisateur, "action", description, date_action FROM __temp__HISTORIQUE_EVENEMENT');
        $this->addSql('DROP TABLE __temp__HISTORIQUE_EVENEMENT');
        $this->addSql('CREATE INDEX IDX_2C47B38D8B13D439 ON HISTORIQUE_EVENEMENT (id_evenement)');
        $this->addSql('CREATE INDEX IDX_2C47B38D50EAE44 ON HISTORIQUE_EVENEMENT (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__HISTORIQUE_STOCK AS SELECT id, id_stock, id_evenement, id_utilisateur, type_changement, quantite, raison, date_creation FROM HISTORIQUE_STOCK');
        $this->addSql('DROP TABLE HISTORIQUE_STOCK');
        $this->addSql('CREATE TABLE HISTORIQUE_STOCK (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_stock INTEGER NOT NULL, id_evenement INTEGER DEFAULT NULL, id_utilisateur INTEGER DEFAULT NULL, type_changement VARCHAR(255) NOT NULL, quantite INTEGER NOT NULL, raison CLOB DEFAULT NULL, date_creation DATETIME DEFAULT NULL, FOREIGN KEY (id_stock) REFERENCES STOCK (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO HISTORIQUE_STOCK (id, id_stock, id_evenement, id_utilisateur, type_changement, quantite, raison, date_creation) SELECT id, id_stock, id_evenement, id_utilisateur, type_changement, quantite, raison, date_creation FROM __temp__HISTORIQUE_STOCK');
        $this->addSql('DROP TABLE __temp__HISTORIQUE_STOCK');
        $this->addSql('CREATE INDEX IDX_76C8B6FBA5B31750 ON HISTORIQUE_STOCK (id_stock)');
        $this->addSql('CREATE INDEX IDX_76C8B6FB8B13D439 ON HISTORIQUE_STOCK (id_evenement)');
        $this->addSql('CREATE INDEX IDX_76C8B6FB50EAE44 ON HISTORIQUE_STOCK (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__INSCRIPTION_MECENE AS SELECT id, id_mecene, id_evenement, description_don, montant_estime, statut, date_inscription, remarques, nom_don, categorie, quantite, valeur_unitaire, remarque_refus FROM INSCRIPTION_MECENE');
        $this->addSql('DROP TABLE INSCRIPTION_MECENE');
        $this->addSql('CREATE TABLE INSCRIPTION_MECENE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_mecene INTEGER NOT NULL, id_evenement INTEGER NOT NULL, description_don CLOB NOT NULL, montant_estime DOUBLE PRECISION DEFAULT NULL, statut VARCHAR(20) NOT NULL, date_inscription DATETIME NOT NULL, remarques CLOB DEFAULT NULL, nom_don VARCHAR(255) NOT NULL, categorie VARCHAR(50) NOT NULL, quantite INTEGER NOT NULL, valeur_unitaire DOUBLE PRECISION DEFAULT NULL, remarque_refus CLOB DEFAULT NULL, FOREIGN KEY (id_mecene) REFERENCES MECENE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO INSCRIPTION_MECENE (id, id_mecene, id_evenement, description_don, montant_estime, statut, date_inscription, remarques, nom_don, categorie, quantite, valeur_unitaire, remarque_refus) SELECT id, id_mecene, id_evenement, description_don, montant_estime, statut, date_inscription, remarques, nom_don, categorie, quantite, valeur_unitaire, remarque_refus FROM __temp__INSCRIPTION_MECENE');
        $this->addSql('DROP TABLE __temp__INSCRIPTION_MECENE');
        $this->addSql('CREATE INDEX IDX_35E63F33D364722F ON INSCRIPTION_MECENE (id_mecene)');
        $this->addSql('CREATE INDEX IDX_35E63F338B13D439 ON INSCRIPTION_MECENE (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__LOT AS SELECT id, id_mecene, titre, description, quantite, valeur_estimee, date_creation FROM LOT');
        $this->addSql('DROP TABLE LOT');
        $this->addSql('CREATE TABLE LOT (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_mecene INTEGER DEFAULT NULL, id_weekend INTEGER DEFAULT NULL, titre VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, quantite INTEGER NOT NULL, valeur_estimee DOUBLE PRECISION NOT NULL, date_creation DATETIME DEFAULT NULL, FOREIGN KEY (id_mecene) REFERENCES MECENE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9D266B91704F64DE FOREIGN KEY (id_weekend) REFERENCES WEEKEND (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO LOT (id, id_mecene, titre, description, quantite, valeur_estimee, date_creation) SELECT id, id_mecene, titre, description, quantite, valeur_estimee, date_creation FROM __temp__LOT');
        $this->addSql('DROP TABLE __temp__LOT');
        $this->addSql('CREATE INDEX IDX_9D266B91D364722F ON LOT (id_mecene)');
        $this->addSql('CREATE INDEX IDX_9D266B91704F64DE ON LOT (id_weekend)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__MECENE AS SELECT id, id_utilisateur, organisation, siret FROM MECENE');
        $this->addSql('DROP TABLE MECENE');
        $this->addSql('CREATE TABLE MECENE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_utilisateur INTEGER DEFAULT NULL, organisation VARCHAR(255) DEFAULT NULL, siret VARCHAR(50) DEFAULT NULL, FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO MECENE (id, id_utilisateur, organisation, siret) SELECT id, id_utilisateur, organisation, siret FROM __temp__MECENE');
        $this->addSql('DROP TABLE __temp__MECENE');
        $this->addSql('CREATE INDEX IDX_5AB004450EAE44 ON MECENE (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__NOTIFICATION AS SELECT id, id_destinataire, type, message, lien, lue, created_at FROM NOTIFICATION');
        $this->addSql('DROP TABLE NOTIFICATION');
        $this->addSql('CREATE TABLE NOTIFICATION (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_destinataire INTEGER NOT NULL, type VARCHAR(50) NOT NULL, message CLOB NOT NULL, lien VARCHAR(255) DEFAULT NULL, lue BOOLEAN DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, FOREIGN KEY (id_destinataire) REFERENCES UTILISATEUR (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO NOTIFICATION (id, id_destinataire, type, message, lien, lue, created_at) SELECT id, id_destinataire, type, message, lien, lue, created_at FROM __temp__NOTIFICATION');
        $this->addSql('DROP TABLE __temp__NOTIFICATION');
        $this->addSql('CREATE INDEX IDX_2A663FDADD688AE0 ON NOTIFICATION (id_destinataire)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__PARAMETRE AS SELECT id, cle, valeur, date_modification FROM PARAMETRE');
        $this->addSql('DROP TABLE PARAMETRE');
        $this->addSql('CREATE TABLE PARAMETRE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, cle VARCHAR(255) NOT NULL, valeur VARCHAR(255) DEFAULT NULL, date_modification DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO PARAMETRE (id, cle, valeur, date_modification) SELECT id, cle, valeur, date_modification FROM __temp__PARAMETRE');
        $this->addSql('DROP TABLE __temp__PARAMETRE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8058EAE41401D17 ON PARAMETRE (cle)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ROLE AS SELECT id, nom, description FROM ROLE');
        $this->addSql('DROP TABLE ROLE');
        $this->addSql('CREATE TABLE ROLE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL)');
        $this->addSql('INSERT INTO ROLE (id, nom, description) SELECT id, nom, description FROM __temp__ROLE');
        $this->addSql('DROP TABLE __temp__ROLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_61FC67DE6C6E55B5 ON ROLE (nom)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__STOCK AS SELECT id, nom, categorie, quantite, unite, seuil, valeur_unitaire, remarque, derniere_modif FROM STOCK');
        $this->addSql('DROP TABLE STOCK');
        $this->addSql('CREATE TABLE STOCK (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, categorie VARCHAR(50) DEFAULT NULL, quantite INTEGER DEFAULT 0 NOT NULL, unite VARCHAR(255) DEFAULT NULL, seuil INTEGER DEFAULT 0 NOT NULL, valeur_unitaire DOUBLE PRECISION DEFAULT \'0\' NOT NULL, remarque CLOB DEFAULT NULL, derniere_modif DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL)');
        $this->addSql('INSERT INTO STOCK (id, nom, categorie, quantite, unite, seuil, valeur_unitaire, remarque, derniere_modif) SELECT id, nom, categorie, quantite, unite, seuil, valeur_unitaire, remarque, derniere_modif FROM __temp__STOCK');
        $this->addSql('DROP TABLE __temp__STOCK');
        $this->addSql('CREATE TEMPORARY TABLE __temp__TACHE AS SELECT id, id_weekend, titre, poste_requis, debut, fin, max_personnes, remarque FROM TACHE');
        $this->addSql('DROP TABLE TACHE');
        $this->addSql('CREATE TABLE TACHE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_weekend INTEGER NOT NULL, titre VARCHAR(255) NOT NULL, poste_requis VARCHAR(100) DEFAULT NULL, debut DATETIME NOT NULL, fin DATETIME NOT NULL, max_personnes INTEGER DEFAULT NULL, remarque CLOB DEFAULT NULL, FOREIGN KEY (id_weekend) REFERENCES WEEKEND (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO TACHE (id, id_weekend, titre, poste_requis, debut, fin, max_personnes, remarque) SELECT id, id_weekend, titre, poste_requis, debut, fin, max_personnes, remarque FROM __temp__TACHE');
        $this->addSql('DROP TABLE __temp__TACHE');
        $this->addSql('CREATE INDEX IDX_64D3E2C5704F64DE ON TACHE (id_weekend)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__UTILISATEUR AS SELECT id, id_role, email, mot_de_passe, prenom, nom, telephone, date_creation, date_modification FROM UTILISATEUR');
        $this->addSql('DROP TABLE UTILISATEUR');
        $this->addSql('CREATE TABLE UTILISATEUR (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_role INTEGER NOT NULL, email VARCHAR(180) NOT NULL, mot_de_passe VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, date_modification DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (id_role) REFERENCES ROLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO UTILISATEUR (id, id_role, email, mot_de_passe, prenom, nom, telephone, date_creation, date_modification) SELECT id, id_role, email, mot_de_passe, prenom, nom, telephone, date_creation, date_modification FROM __temp__UTILISATEUR');
        $this->addSql('DROP TABLE __temp__UTILISATEUR');
        $this->addSql('CREATE INDEX IDX_901FF15BDC499668 ON UTILISATEUR (id_role)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_901FF15BE7927C74 ON UTILISATEUR (email)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__WEEKEND AS SELECT id, nom, cover_image, date_creation FROM WEEKEND');
        $this->addSql('DROP TABLE WEEKEND');
        $this->addSql('CREATE TABLE WEEKEND (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, cover_image VARCHAR(255) DEFAULT NULL, date_creation DATETIME NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL)');
        $this->addSql('INSERT INTO WEEKEND (id, nom, cover_image, date_creation) SELECT id, nom, cover_image, date_creation FROM __temp__WEEKEND');
        $this->addSql('DROP TABLE __temp__WEEKEND');
        $this->addSql('CREATE TEMPORARY TABLE __temp__messenger_messages AS SELECT id, body, headers, queue_name, created_at, available_at, delivered_at FROM messenger_messages');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , available_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , delivered_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
        )');
        $this->addSql('INSERT INTO messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) SELECT id, body, headers, queue_name, created_at, available_at, delivered_at FROM __temp__messenger_messages');
        $this->addSql('DROP TABLE __temp__messenger_messages');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE CRENEAU');
        $this->addSql('CREATE TEMPORARY TABLE __temp__AFFECTATION_TACHE AS SELECT id, id_tache, id_benevole, id_utilisateur, date_affectation, statut, remarque FROM AFFECTATION_TACHE');
        $this->addSql('DROP TABLE AFFECTATION_TACHE');
        $this->addSql('CREATE TABLE AFFECTATION_TACHE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_tache INTEGER NOT NULL, id_benevole INTEGER NOT NULL, id_utilisateur INTEGER DEFAULT NULL, date_affectation DATETIME DEFAULT CURRENT_TIMESTAMP, statut CLOB DEFAULT \'assigne\', remarque CLOB DEFAULT NULL, CONSTRAINT FK_12694ECF7D026145 FOREIGN KEY (id_tache) REFERENCES TACHE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_12694ECFE4DAA34E FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_12694ECF50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO AFFECTATION_TACHE (id, id_tache, id_benevole, id_utilisateur, date_affectation, statut, remarque) SELECT id, id_tache, id_benevole, id_utilisateur, date_affectation, statut, remarque FROM __temp__AFFECTATION_TACHE');
        $this->addSql('DROP TABLE __temp__AFFECTATION_TACHE');
        $this->addSql('CREATE INDEX IDX_12694ECF7D026145 ON AFFECTATION_TACHE (id_tache)');
        $this->addSql('CREATE INDEX IDX_12694ECFE4DAA34E ON AFFECTATION_TACHE (id_benevole)');
        $this->addSql('CREATE INDEX IDX_12694ECF50EAE44 ON AFFECTATION_TACHE (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__BENEVOLE AS SELECT id, id_utilisateur, remarque, actif FROM BENEVOLE');
        $this->addSql('DROP TABLE BENEVOLE');
        $this->addSql('CREATE TABLE BENEVOLE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_utilisateur INTEGER NOT NULL, remarque CLOB DEFAULT NULL, actif BOOLEAN DEFAULT 1, CONSTRAINT FK_7232D39750EAE44 FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO BENEVOLE (id, id_utilisateur, remarque, actif) SELECT id, id_utilisateur, remarque, actif FROM __temp__BENEVOLE');
        $this->addSql('DROP TABLE __temp__BENEVOLE');
        $this->addSql('CREATE INDEX IDX_7232D39750EAE44 ON BENEVOLE (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__COMMUNICATION AS SELECT id, id_evenement, titre, type, date_prevue, statut, budget, notes, date_creation FROM COMMUNICATION');
        $this->addSql('DROP TABLE COMMUNICATION');
        $this->addSql('CREATE TABLE COMMUNICATION (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_evenement INTEGER DEFAULT NULL, titre CLOB NOT NULL, type CLOB DEFAULT \'post\', date_prevue DATETIME DEFAULT NULL, statut CLOB DEFAULT \'brouillon\', budget DOUBLE PRECISION DEFAULT \'0.0\', remarque CLOB DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_DFE3B70E8B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO COMMUNICATION (id, id_evenement, titre, type, date_prevue, statut, budget, remarque, date_creation) SELECT id, id_evenement, titre, type, date_prevue, statut, budget, notes, date_creation FROM __temp__COMMUNICATION');
        $this->addSql('DROP TABLE __temp__COMMUNICATION');
        $this->addSql('CREATE INDEX IDX_DFE3B70E8B13D439 ON COMMUNICATION (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__CONTACT_MESSAGE AS SELECT id, repondu_par_id, nom, email, message, created_at, lu, reponse, repondu_le FROM CONTACT_MESSAGE');
        $this->addSql('DROP TABLE CONTACT_MESSAGE');
        $this->addSql('CREATE TABLE CONTACT_MESSAGE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, repondu_par_id INTEGER DEFAULT NULL, nom CLOB NOT NULL, email CLOB NOT NULL, message CLOB NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, lu BOOLEAN DEFAULT 0, reponse CLOB DEFAULT NULL, repondu_le DATETIME DEFAULT NULL, CONSTRAINT FK_B609370B26CA41A0 FOREIGN KEY (repondu_par_id) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO CONTACT_MESSAGE (id, repondu_par_id, nom, email, message, created_at, lu, reponse, repondu_le) SELECT id, repondu_par_id, nom, email, message, created_at, lu, reponse, repondu_le FROM __temp__CONTACT_MESSAGE');
        $this->addSql('DROP TABLE __temp__CONTACT_MESSAGE');
        $this->addSql('CREATE INDEX IDX_B609370B26CA41A0 ON CONTACT_MESSAGE (repondu_par_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__CONVENTION AS SELECT id, id_mecene, nom_modele, url_pdf, date_signature, methode_signature, date_creation FROM CONVENTION');
        $this->addSql('DROP TABLE CONVENTION');
        $this->addSql('CREATE TABLE CONVENTION (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_mecene INTEGER NOT NULL, nom_modele CLOB DEFAULT NULL, url_pdf CLOB DEFAULT NULL, date_signature DATETIME DEFAULT NULL, methode_signature CLOB DEFAULT \'aucune\', date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_8EC97841D364722F FOREIGN KEY (id_mecene) REFERENCES MECENE (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO CONVENTION (id, id_mecene, nom_modele, url_pdf, date_signature, methode_signature, date_creation) SELECT id, id_mecene, nom_modele, url_pdf, date_signature, methode_signature, date_creation FROM __temp__CONVENTION');
        $this->addSql('DROP TABLE __temp__CONVENTION');
        $this->addSql('CREATE INDEX IDX_8EC97841D364722F ON CONVENTION (id_mecene)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__DEMANDE_ANNULATION AS SELECT id, id_affectation, id_benevole, id_admin_reponse, date_demande, statut, motif_benevole, message_admin, date_reponse FROM DEMANDE_ANNULATION');
        $this->addSql('DROP TABLE DEMANDE_ANNULATION');
        $this->addSql('CREATE TABLE DEMANDE_ANNULATION (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_affectation INTEGER NOT NULL, id_benevole INTEGER NOT NULL, id_admin_reponse INTEGER DEFAULT NULL, date_demande DATETIME DEFAULT CURRENT_TIMESTAMP, statut CLOB DEFAULT \'en_attente\', motif_benevole CLOB DEFAULT NULL, message_admin CLOB DEFAULT NULL, date_reponse DATETIME DEFAULT NULL, CONSTRAINT FK_75084DE6ECCFAC24 FOREIGN KEY (id_affectation) REFERENCES AFFECTATION_TACHE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_75084DE6E4DAA34E FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_75084DE625A28D2B FOREIGN KEY (id_admin_reponse) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO DEMANDE_ANNULATION (id, id_affectation, id_benevole, id_admin_reponse, date_demande, statut, motif_benevole, message_admin, date_reponse) SELECT id, id_affectation, id_benevole, id_admin_reponse, date_demande, statut, motif_benevole, message_admin, date_reponse FROM __temp__DEMANDE_ANNULATION');
        $this->addSql('DROP TABLE __temp__DEMANDE_ANNULATION');
        $this->addSql('CREATE INDEX IDX_75084DE6ECCFAC24 ON DEMANDE_ANNULATION (id_affectation)');
        $this->addSql('CREATE INDEX IDX_75084DE6E4DAA34E ON DEMANDE_ANNULATION (id_benevole)');
        $this->addSql('CREATE INDEX IDX_75084DE625A28D2B ON DEMANDE_ANNULATION (id_admin_reponse)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__DEMANDE_TACHE AS SELECT id, id_tache, id_benevole, id_admin_reponse, date_demande, statut, message_benevole, message_admin, date_reponse FROM DEMANDE_TACHE');
        $this->addSql('DROP TABLE DEMANDE_TACHE');
        $this->addSql('CREATE TABLE DEMANDE_TACHE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_tache INTEGER NOT NULL, id_benevole INTEGER NOT NULL, id_admin_reponse INTEGER DEFAULT NULL, date_demande DATETIME DEFAULT CURRENT_TIMESTAMP, statut CLOB DEFAULT \'en_attente\', message_benevole CLOB DEFAULT NULL, message_admin CLOB DEFAULT NULL, date_reponse DATETIME DEFAULT NULL, CONSTRAINT FK_44B9A48F7D026145 FOREIGN KEY (id_tache) REFERENCES TACHE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_44B9A48FE4DAA34E FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_44B9A48F25A28D2B FOREIGN KEY (id_admin_reponse) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO DEMANDE_TACHE (id, id_tache, id_benevole, id_admin_reponse, date_demande, statut, message_benevole, message_admin, date_reponse) SELECT id, id_tache, id_benevole, id_admin_reponse, date_demande, statut, message_benevole, message_admin, date_reponse FROM __temp__DEMANDE_TACHE');
        $this->addSql('DROP TABLE __temp__DEMANDE_TACHE');
        $this->addSql('CREATE INDEX IDX_44B9A48F7D026145 ON DEMANDE_TACHE (id_tache)');
        $this->addSql('CREATE INDEX IDX_44B9A48FE4DAA34E ON DEMANDE_TACHE (id_benevole)');
        $this->addSql('CREATE INDEX IDX_44B9A48F25A28D2B ON DEMANDE_TACHE (id_admin_reponse)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__DISPONIBILITE_BENEVOLE AS SELECT id, id_benevole, id_evenement, debut, fin, notes, date_creation FROM DISPONIBILITE_BENEVOLE');
        $this->addSql('DROP TABLE DISPONIBILITE_BENEVOLE');
        $this->addSql('CREATE TABLE DISPONIBILITE_BENEVOLE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_benevole INTEGER NOT NULL, id_evenement INTEGER NOT NULL, debut DATETIME DEFAULT NULL, fin DATETIME DEFAULT NULL, remarque CLOB DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_FA2761DCE4DAA34E FOREIGN KEY (id_benevole) REFERENCES BENEVOLE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_FA2761DC8B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO DISPONIBILITE_BENEVOLE (id, id_benevole, id_evenement, debut, fin, remarque, date_creation) SELECT id, id_benevole, id_evenement, debut, fin, notes, date_creation FROM __temp__DISPONIBILITE_BENEVOLE');
        $this->addSql('DROP TABLE __temp__DISPONIBILITE_BENEVOLE');
        $this->addSql('CREATE INDEX IDX_FA2761DCE4DAA34E ON DISPONIBILITE_BENEVOLE (id_benevole)');
        $this->addSql('CREATE INDEX IDX_FA2761DC8B13D439 ON DISPONIBILITE_BENEVOLE (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__EVENEMENT AS SELECT id, id_weekend, nom, description, date_debut, date_fin, lieu, heure_debut, duree_minutes, image, date_creation FROM EVENEMENT');
        $this->addSql('DROP TABLE EVENEMENT');
        $this->addSql('CREATE TABLE EVENEMENT (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_weekend INTEGER DEFAULT NULL, nom CLOB NOT NULL, description CLOB DEFAULT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, lieu CLOB DEFAULT NULL, heure_debut TIME DEFAULT NULL, duree_minutes INTEGER DEFAULT NULL, image CLOB DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_4FE476F1704F64DE FOREIGN KEY (id_weekend) REFERENCES WEEKEND (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO EVENEMENT (id, id_weekend, nom, description, date_debut, date_fin, lieu, heure_debut, duree_minutes, image, date_creation) SELECT id, id_weekend, nom, description, date_debut, date_fin, lieu, heure_debut, duree_minutes, image, date_creation FROM __temp__EVENEMENT');
        $this->addSql('DROP TABLE __temp__EVENEMENT');
        $this->addSql('CREATE INDEX IDX_4FE476F1704F64DE ON EVENEMENT (id_weekend)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__HELLOASSO AS SELECT id, id_evenement, id_externe, prenom, nom, email, telephone, type_ticket, date_achat, date_import FROM HELLOASSO');
        $this->addSql('DROP TABLE HELLOASSO');
        $this->addSql('CREATE TABLE HELLOASSO (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_evenement INTEGER DEFAULT NULL, id_externe CLOB DEFAULT NULL, prenom CLOB DEFAULT NULL, nom CLOB DEFAULT NULL, email CLOB DEFAULT NULL, telephone CLOB DEFAULT NULL, type_ticket CLOB DEFAULT NULL, date_achat DATETIME DEFAULT NULL, date_import DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_F90B9E9D8B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO HELLOASSO (id, id_evenement, id_externe, prenom, nom, email, telephone, type_ticket, date_achat, date_import) SELECT id, id_evenement, id_externe, prenom, nom, email, telephone, type_ticket, date_achat, date_import FROM __temp__HELLOASSO');
        $this->addSql('DROP TABLE __temp__HELLOASSO');
        $this->addSql('CREATE INDEX IDX_F90B9E9D8B13D439 ON HELLOASSO (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__HISTORIQUE_EVENEMENT AS SELECT id, id_evenement, id_utilisateur, "action", description, date_action FROM HISTORIQUE_EVENEMENT');
        $this->addSql('DROP TABLE HISTORIQUE_EVENEMENT');
        $this->addSql('CREATE TABLE HISTORIQUE_EVENEMENT (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_evenement INTEGER NOT NULL, id_utilisateur INTEGER DEFAULT NULL, "action" CLOB NOT NULL, description CLOB DEFAULT NULL, date_action DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_2C47B38D8B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_2C47B38D50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO HISTORIQUE_EVENEMENT (id, id_evenement, id_utilisateur, "action", description, date_action) SELECT id, id_evenement, id_utilisateur, "action", description, date_action FROM __temp__HISTORIQUE_EVENEMENT');
        $this->addSql('DROP TABLE __temp__HISTORIQUE_EVENEMENT');
        $this->addSql('CREATE INDEX IDX_2C47B38D8B13D439 ON HISTORIQUE_EVENEMENT (id_evenement)');
        $this->addSql('CREATE INDEX IDX_2C47B38D50EAE44 ON HISTORIQUE_EVENEMENT (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__HISTORIQUE_STOCK AS SELECT id, id_stock, id_evenement, id_utilisateur, type_changement, quantite, raison, date_creation FROM HISTORIQUE_STOCK');
        $this->addSql('DROP TABLE HISTORIQUE_STOCK');
        $this->addSql('CREATE TABLE HISTORIQUE_STOCK (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_stock INTEGER NOT NULL, id_evenement INTEGER DEFAULT NULL, id_utilisateur INTEGER DEFAULT NULL, type_changement CLOB NOT NULL, quantite INTEGER NOT NULL, raison CLOB DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_76C8B6FBA5B31750 FOREIGN KEY (id_stock) REFERENCES STOCK (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_76C8B6FB8B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_76C8B6FB50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO HISTORIQUE_STOCK (id, id_stock, id_evenement, id_utilisateur, type_changement, quantite, raison, date_creation) SELECT id, id_stock, id_evenement, id_utilisateur, type_changement, quantite, raison, date_creation FROM __temp__HISTORIQUE_STOCK');
        $this->addSql('DROP TABLE __temp__HISTORIQUE_STOCK');
        $this->addSql('CREATE INDEX IDX_76C8B6FBA5B31750 ON HISTORIQUE_STOCK (id_stock)');
        $this->addSql('CREATE INDEX IDX_76C8B6FB8B13D439 ON HISTORIQUE_STOCK (id_evenement)');
        $this->addSql('CREATE INDEX IDX_76C8B6FB50EAE44 ON HISTORIQUE_STOCK (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__INSCRIPTION_MECENE AS SELECT id, id_mecene, id_evenement, description_don, montant_estime, statut, date_inscription, remarques, nom_don, categorie, quantite, valeur_unitaire, remarque_refus FROM INSCRIPTION_MECENE');
        $this->addSql('DROP TABLE INSCRIPTION_MECENE');
        $this->addSql('CREATE TABLE INSCRIPTION_MECENE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_mecene INTEGER NOT NULL, id_evenement INTEGER NOT NULL, description_don CLOB NOT NULL, montant_estime DOUBLE PRECISION DEFAULT NULL, statut CLOB DEFAULT \'en_attente\', date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP, remarques CLOB DEFAULT NULL, nom_don CLOB NOT NULL, categorie CLOB NOT NULL, quantite INTEGER NOT NULL, valeur_unitaire DOUBLE PRECISION DEFAULT NULL, remarque_refus CLOB DEFAULT NULL, CONSTRAINT FK_35E63F33D364722F FOREIGN KEY (id_mecene) REFERENCES MECENE (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_35E63F338B13D439 FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO INSCRIPTION_MECENE (id, id_mecene, id_evenement, description_don, montant_estime, statut, date_inscription, remarques, nom_don, categorie, quantite, valeur_unitaire, remarque_refus) SELECT id, id_mecene, id_evenement, description_don, montant_estime, statut, date_inscription, remarques, nom_don, categorie, quantite, valeur_unitaire, remarque_refus FROM __temp__INSCRIPTION_MECENE');
        $this->addSql('DROP TABLE __temp__INSCRIPTION_MECENE');
        $this->addSql('CREATE INDEX IDX_35E63F33D364722F ON INSCRIPTION_MECENE (id_mecene)');
        $this->addSql('CREATE INDEX IDX_35E63F338B13D439 ON INSCRIPTION_MECENE (id_evenement)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__LOT AS SELECT id, id_mecene, titre, description, quantite, valeur_estimee, date_creation FROM LOT');
        $this->addSql('DROP TABLE LOT');
        $this->addSql('CREATE TABLE LOT (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_mecene INTEGER DEFAULT NULL, titre CLOB NOT NULL, description CLOB DEFAULT NULL, quantite INTEGER DEFAULT 1, valeur_estimee DOUBLE PRECISION DEFAULT \'0.0\', date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_9D266B91D364722F FOREIGN KEY (id_mecene) REFERENCES MECENE (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO LOT (id, id_mecene, titre, description, quantite, valeur_estimee, date_creation) SELECT id, id_mecene, titre, description, quantite, valeur_estimee, date_creation FROM __temp__LOT');
        $this->addSql('DROP TABLE __temp__LOT');
        $this->addSql('CREATE INDEX IDX_9D266B91D364722F ON LOT (id_mecene)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__MECENE AS SELECT id, id_utilisateur, organisation, siret FROM MECENE');
        $this->addSql('DROP TABLE MECENE');
        $this->addSql('CREATE TABLE MECENE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_utilisateur INTEGER DEFAULT NULL, organisation CLOB NOT NULL, siret CLOB NOT NULL, CONSTRAINT FK_5AB004450EAE44 FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO MECENE (id, id_utilisateur, organisation, siret) SELECT id, id_utilisateur, organisation, siret FROM __temp__MECENE');
        $this->addSql('DROP TABLE __temp__MECENE');
        $this->addSql('CREATE INDEX IDX_5AB004450EAE44 ON MECENE (id_utilisateur)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__NOTIFICATION AS SELECT id, id_destinataire, type, message, lien, lue, created_at FROM NOTIFICATION');
        $this->addSql('DROP TABLE NOTIFICATION');
        $this->addSql('CREATE TABLE NOTIFICATION (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_destinataire INTEGER NOT NULL, type VARCHAR(50) NOT NULL, message CLOB NOT NULL, lien VARCHAR(255) DEFAULT NULL, lue BOOLEAN DEFAULT 0, created_at DATETIME NOT NULL, CONSTRAINT FK_2A663FDADD688AE0 FOREIGN KEY (id_destinataire) REFERENCES UTILISATEUR (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO NOTIFICATION (id, id_destinataire, type, message, lien, lue, created_at) SELECT id, id_destinataire, type, message, lien, lue, created_at FROM __temp__NOTIFICATION');
        $this->addSql('DROP TABLE __temp__NOTIFICATION');
        $this->addSql('CREATE INDEX IDX_2A663FDADD688AE0 ON NOTIFICATION (id_destinataire)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__PARAMETRE AS SELECT id, cle, valeur, date_modification FROM PARAMETRE');
        $this->addSql('DROP TABLE PARAMETRE');
        $this->addSql('CREATE TABLE PARAMETRE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, cle CLOB NOT NULL, valeur CLOB DEFAULT NULL, date_modification DATETIME DEFAULT CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO PARAMETRE (id, cle, valeur, date_modification) SELECT id, cle, valeur, date_modification FROM __temp__PARAMETRE');
        $this->addSql('DROP TABLE __temp__PARAMETRE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ROLE AS SELECT id, nom, description FROM ROLE');
        $this->addSql('DROP TABLE ROLE');
        $this->addSql('CREATE TABLE ROLE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, nom CLOB NOT NULL, description CLOB DEFAULT NULL)');
        $this->addSql('INSERT INTO ROLE (id, nom, description) SELECT id, nom, description FROM __temp__ROLE');
        $this->addSql('DROP TABLE __temp__ROLE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__STOCK AS SELECT id, nom, categorie, quantite, unite, seuil, valeur_unitaire, remarque, derniere_modif FROM STOCK');
        $this->addSql('DROP TABLE STOCK');
        $this->addSql('CREATE TABLE STOCK (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, nom CLOB NOT NULL, categorie CLOB DEFAULT NULL, quantite INTEGER DEFAULT 0, unite CLOB DEFAULT NULL, seuil INTEGER DEFAULT 0, valeur_unitaire DOUBLE PRECISION DEFAULT \'0.0\', remarque CLOB DEFAULT NULL, derniere_modif DATETIME DEFAULT CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO STOCK (id, nom, categorie, quantite, unite, seuil, valeur_unitaire, remarque, derniere_modif) SELECT id, nom, categorie, quantite, unite, seuil, valeur_unitaire, remarque, derniere_modif FROM __temp__STOCK');
        $this->addSql('DROP TABLE __temp__STOCK');
        $this->addSql('CREATE TEMPORARY TABLE __temp__TACHE AS SELECT id, id_weekend, titre, debut, fin, poste_requis, max_personnes, remarque FROM TACHE');
        $this->addSql('DROP TABLE TACHE');
        $this->addSql('CREATE TABLE TACHE (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_weekend INTEGER NOT NULL, titre CLOB NOT NULL, debut DATETIME NOT NULL, fin DATETIME NOT NULL, poste_requis CLOB DEFAULT NULL, max_personnes INTEGER DEFAULT 1, remarque CLOB DEFAULT NULL, CONSTRAINT FK_64D3E2C5704F64DE FOREIGN KEY (id_weekend) REFERENCES WEEKEND (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO TACHE (id, id_weekend, titre, debut, fin, poste_requis, max_personnes, remarque) SELECT id, id_weekend, titre, debut, fin, poste_requis, max_personnes, remarque FROM __temp__TACHE');
        $this->addSql('DROP TABLE __temp__TACHE');
        $this->addSql('CREATE INDEX IDX_64D3E2C5704F64DE ON TACHE (id_weekend)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__UTILISATEUR AS SELECT id, id_role, email, mot_de_passe, prenom, nom, telephone, date_creation, date_modification FROM UTILISATEUR');
        $this->addSql('DROP TABLE UTILISATEUR');
        $this->addSql('CREATE TABLE UTILISATEUR (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, id_role INTEGER NOT NULL, email CLOB NOT NULL, mot_de_passe CLOB DEFAULT NULL, prenom CLOB DEFAULT NULL, nom CLOB DEFAULT NULL, telephone CLOB DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, date_modification DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_901FF15BDC499668 FOREIGN KEY (id_role) REFERENCES ROLE (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO UTILISATEUR (id, id_role, email, mot_de_passe, prenom, nom, telephone, date_creation, date_modification) SELECT id, id_role, email, mot_de_passe, prenom, nom, telephone, date_creation, date_modification FROM __temp__UTILISATEUR');
        $this->addSql('DROP TABLE __temp__UTILISATEUR');
        $this->addSql('CREATE INDEX IDX_901FF15BDC499668 ON UTILISATEUR (id_role)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__WEEKEND AS SELECT id, nom, date_creation, cover_image FROM WEEKEND');
        $this->addSql('DROP TABLE WEEKEND');
        $this->addSql('CREATE TABLE WEEKEND (id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, nom CLOB NOT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, cover_image CLOB DEFAULT NULL, date_vendredi DATE NOT NULL, date_samedi DATE NOT NULL, date_dimanche DATE NOT NULL)');
        $this->addSql('INSERT INTO WEEKEND (id, nom, date_creation, cover_image) SELECT id, nom, date_creation, cover_image FROM __temp__WEEKEND');
        $this->addSql('DROP TABLE __temp__WEEKEND');
        $this->addSql('CREATE TEMPORARY TABLE __temp__messenger_messages AS SELECT id, body, headers, queue_name, created_at, available_at, delivered_at FROM messenger_messages');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) SELECT id, body, headers, queue_name, created_at, available_at, delivered_at FROM __temp__messenger_messages');
        $this->addSql('DROP TABLE __temp__messenger_messages');
    }
}
