when@dev:
    web_profiler:
        toolbar:
            enabled: '%env(bool:APP_DEBUG)%'

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
