# Ce fichier est utilisé pour surcharger la configuration de développement
# Il n'est plus nécessaire car tout est défini dans compose.yaml
services:
  app:
    environment:
      APP_ENV: dev
      APP_DEBUG: 0
